language: ruby
rvm: 2.2.0
cache:
  bundler: true
  directories:
    - public/assets
bundler_args: --without production

script:
  - bundle exec rubocop --fail-level=W
  - bundle exec rake db:create db:migrate assets:precompile RAILS_ENV=test
  - bundle exec rake test

notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/c30cd42d-fa04-415f-bd46-e6da3fa98850
